name: Build and Publish Apache Polaris Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          repository: apache/polaris
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          # The setup-gradle action fails, if the wrapper is not using the right version or is not present.
          # Our `gradlew` validates the integrity of the `gradle-wrapper.jar`, so it's safe to disable this.
          validate-wrappers: false

      - name: Clean
        run: ./gradlew clean
      - name: Build
        run: ./gradlew compileAll

      - name: Build Polaris Docker image
        run: |
          ./gradlew \
            :polaris-quarkus-server:assemble \
            :polaris-quarkus-server:quarkusAppPartsBuild --rerun \
            -Dquarkus.container-image.build=true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/polaris
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=ref,event=branch
            type=sha,format=short
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
      
      - name: Build and push Docker image
        run: |
          # Tag the locally built image with the ghcr.io path and appropriate tags
          for tag in $(echo "${{ steps.meta.outputs.tags }}" | tr '\n' ' '); do
            docker tag apache/polaris:latest $tag
            docker push $tag
          done
